### PR TITLE
Add social buttons at the team page for email, phone and Whatsapp

### PR DESCRIPTION
**Pull request by Addono**
Would have liked to also include Telegram and Gitlab, however - as also concluded in #13 for Gitlab - these icons are not present in the included icon packs. (Although Telegram is currently part of the latest version of the free icomoon pack).

As all the other links take the full URL instead of just the username (e.g. `github = "https://github.com/Addono"` instead of `github = "Addono"`) did I do the same with the Whatsapp link. However, as it might not be completely trivial for every user might it be nice to include some example link instead of `whatsapp = "#"`. In case one is wondering, Whatsapp links look like `https://web.whatsapp.com/send?phone={phone number}` where the phone number includes the country code without leading zero's or plus sign - for me it would be `https://web.whatsapp.com/send?phone=31640410001`.

Anyway, thanks for the port! It's nice.

### CODE REVIEW

**Comment by SteveLane** [comment]
OK, people can see this now, so thanks for writing in.

**Comment by Addono** [comment]
From your response I am not entirely sure that you that the PR still adds support for phone, email and Whatsapp. If you don't want to support them by default, then that is fine. Just made the PR as I wanted it for my own project and I can image that others have similar needs.

**Comment by SteveLane** [comment]
Yeah, but you'd closed the PR and deleted the branch, so I left it at that.

**Comment by Addono** [comment]
Aah, my bad. Wasn't the intention, I restored the branch. Can you re-open the PR or should I make a new one?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SteveLane** [comment]
OK, done, thanks for your additions. I'm going to leave the config file as it is, a quick search through the repo will find these examples. Cheers

**Pull request merged**
